name: OpTools
version: '${project.version}'
main: me.adamwierzbanowski.optools.OpTools
api-version: 1.19
description: Adds Operator Tools
commands:
  God:
    description: Makes you or the given player invulnerable
    usage: /<command> Player
  TimeBan:
    description: Bans the given player for a chosen amount of time
    usage: /<command> Player Reason
